sonar.projectKey=intechcore_container-healthcheck
sonar.organization=intechcore
sonar.projectName=container-healthcheck

sonar.sources=.
sonar.exclusions=**/*_test.go,tests/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go,tests/**
sonar.go.coverage.reportPaths=coverage.out
